# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\pyqt_learning\ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 390)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 421, 391))
        self.tabWidget.setIconSize(QtCore.QSize(26, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.resultGroupBox = QtWidgets.QGroupBox(self.mainPage)
        self.resultGroupBox.setGeometry(QtCore.QRect(0, 230, 411, 141))
        self.resultGroupBox.setObjectName("resultGroupBox")
        self.resultText = QtWidgets.QTextEdit(self.resultGroupBox)
        self.resultText.setGeometry(QtCore.QRect(10, 20, 391, 111))
        self.resultText.setAutoFillBackground(False)
        self.resultText.setObjectName("resultText")
        self.imageLabel = QtWidgets.QLabel(self.mainPage)
        self.imageLabel.setGeometry(QtCore.QRect(10, 10, 391, 211))
        self.imageLabel.setAcceptDrops(True)
        self.imageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.imageLabel.setAutoFillBackground(True)
        self.imageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imageLabel.setTextFormat(QtCore.Qt.PlainText)
        self.imageLabel.setScaledContents(False)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setWordWrap(False)
        self.imageLabel.setOpenExternalLinks(False)
        self.imageLabel.setObjectName("imageLabel")
        self.tabWidget.addTab(self.mainPage, "")
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.textBrowser = QtWidgets.QTextBrowser(self.aboutPage)
        self.textBrowser.setGeometry(QtCore.QRect(80, 40, 256, 192))
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.aboutPage, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "pyzxing-GUI"))
        self.resultGroupBox.setTitle(_translate("Form", "Result"))
        self.imageLabel.setText(_translate("Form", "Drop file here"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainPage), _translate("Form", "Main"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/ChenjieXu/pyzxing-GUI\"><span style=\" text-decoration: underline; color:#0000ff;\">pyzxing-GUI</span></a> Version:v0.1</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Backend: <a href=\"https://github.com/ChenjieXu/pyzxing\"><span style=\" text-decoration: underline; color:#0000ff;\">pyzxing</span></a> Version:v0.3.3</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">Coded by:</span> <a href=\"https://github.com/ChenjieXu\"><span style=\" text-decoration: underline; color:#0000ff;\">Chenjie Xu</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutPage), _translate("Form", "About"))
